// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoxatObl2KZMTpJtg5snBDxO4t9ALpUT8',
    appId: '1:544665446027:web:0207b2181ff15af32d168e',
    messagingSenderId: '544665446027',
    projectId: 'el-3yada',
    authDomain: 'el-3yada.firebaseapp.com',
    storageBucket: 'el-3yada.firebasestorage.app',
    measurementId: 'G-81JBDM74Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7SdOJy2iwkLhynK5MLWdhnqWlmgXo2po',
    appId: '1:544665446027:android:2c4481f235470cee2d168e',
    messagingSenderId: '544665446027',
    projectId: 'el-3yada',
    storageBucket: 'el-3yada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPRz_GLBEf63RyrxO2Ej31-Hl9HSZ2JpU',
    appId: '1:544665446027:ios:8aea2ef2117441572d168e',
    messagingSenderId: '544665446027',
    projectId: 'el-3yada',
    storageBucket: 'el-3yada.firebasestorage.app',
    iosBundleId: 'com.example.myDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPRz_GLBEf63RyrxO2Ej31-Hl9HSZ2JpU',
    appId: '1:544665446027:ios:8aea2ef2117441572d168e',
    messagingSenderId: '544665446027',
    projectId: 'el-3yada',
    storageBucket: 'el-3yada.firebasestorage.app',
    iosBundleId: 'com.example.myDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoxatObl2KZMTpJtg5snBDxO4t9ALpUT8',
    appId: '1:544665446027:web:a92af7f2364b34292d168e',
    messagingSenderId: '544665446027',
    projectId: 'el-3yada',
    authDomain: 'el-3yada.firebaseapp.com',
    storageBucket: 'el-3yada.firebasestorage.app',
    measurementId: 'G-GBH03WKPJR',
  );
}
